version: '3.8'

services:
  dynamodb-local:
    image: amazon/dynamodb-local:2.5.4
    container_name: square-feet-dynamodb
    ports:
      - '8000:8000'
    environment:
      - AWS_ACCESS_KEY_ID=local
      - AWS_SECRET_ACCESS_KEY=local
    volumes:
      - ./dynamodb-data:/home/dynamodblocal/data
    command: -jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal/data
